title    Custom Arch Linux KDE Live (linux-lts) - Copy to RAM (%ARCH%, UEFI)
sort-key 05
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-lts
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-lts.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% copytoram=y cow_spacesize=4G %KERNEL_PARAMS%
