title    Custom Arch Linux KDE Live (linux-lts) (%ARCH%, UEFI) with speech
sort-key 06
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-lts
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-lts.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% copytoram=n cow_spacesize=4G accessibility=on %KERNEL_PARAMS%
